language: python
services:
  - docker

before_install:  
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -q -o Dpkg::Options::="--force-confnew" install -y docker-engine

script:
    - docker build -t test .
