name: python2
channels:
- bioconda
- conda-forge
dependencies:
# bioconda
- zeroc-ice=3.6.3=py27_0
# conda-forge
- ipywidgets=7.4.*
- matplotlib=2.2.*
- nbval=0.9.*
- pandas=0.23.*
- pillow=5.*
- pytables=3.4.*
- pytest=3.3.*
- python=2.7.*
- scikit-image=0.14.*
- scipy=1.1.*
