name: python2
channels:
- bioconda
- conda-forge
- defaults
dependencies:
# bioconda
- idr-py=0.2.0=py27_0
- gseapy=0.9.2=py27_0
- python-omero=5.3.3=py27_0
- zeroc-ice=3.6.3=py27_0
# conda-forge
- bokeh=0.12.11=py27_0
- ipywidgets=7.0.5=py27_0
- joblib=0.11=py27_0
- markdown=2.6.9=py27_0
- matplotlib=2.0.2=py27_2
- pandas=0.21.0=py27_0
- pillow=4.2.1=py27_0
- psutil=5.4.0=py27_0
- pytables=3.4.2=py27_7
- pytest=3.3.0=py27_0
- python-graphviz=0.8.2=py27_0
- python-igraph=0.7.1.post6=py27_4
- scikit-image=0.13.0=py27_3
- scikit-learn=0.19.1=py27_blas_openblas_201
- scipy=1.0.0=py27_blas_openblas_201
- seaborn=0.8.1=py27_0
- tqdm=4.19.5=py_0
# defaults
- pydot=1.2.4=py_0
- pip:
  - py2cytoscape==0.6.2
